platform :ios, '11.0'

target :DBGHTMLEntitiesExample do
  pod "DBGHTMLEntities", :path => "../DBGHTMLEntities.podspec"
end

target :DBGHTMLEntitiesExampleTests do
  pod 'Specta',  '~> 1.0'
  pod 'Expecta', '~> 1.0'
end

