platform :ios, '11.0'

target :DBGHTMLEntitiesExample do
  pod "DBGHTMLEntities", :path => "../DBGHTMLEntities.podspec"
  pod 'ORStackView'
end

target :DBGHTMLEntitiesExampleTests do
  pod 'Specta',      '~> 0.2.1'
  pod 'Expecta',     '~> 0.3.0'
end

