name: "DBGHTMLEntities CI"

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '*'

jobs:
  Example:
    name: Example Project (Latest Stable Xcode)
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with: 
          xcode-version: latest-stable

      - name: Run pod install
        run: pod install --project-directory=Example

      - name: Build Project
        uses: sersoft-gmbh/xcodebuild-action@v1.8.0
        with:
          workspace: Example/DBGHTMLEntitiesExample.xcworkspace
          scheme: DBGHTMLEntitiesExample
          destination: name=iPhone 13 Pro
          action: test

  Pods:
    name: Cocoapods Lint (Latest Stable Xcode)
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with: 
          xcode-version: latest-stable

      - name: Run pod lib lint
        run: pod lib lint --fail-fast
          
  SwiftPM:
    name: SwiftPM (Latest Stable Xcode)
    runs-on: macOS-11
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1.4.0
        with: 
          xcode-version: latest-stable 

      - name: Build
        run: swift build
